language: python
services:
  - mysql
python:
  - "3.7"
before_install:
  - sudo mysql -e 'CREATE DATABASE magic;'
install:
  - pip install -r requirements/requirements.txt
script:
  - python ./tools/init_db.py
  - python server.py
